### ISSUE TITLE
Основные Правки:

### ISSUE THREAD

**Issue by Samaeldll** [Samaeldll/Corew#4]
1 - Вместо сообщения "Вам нужно иметь группу или рейд.....". Выводиться: 3
2 - Нет оповещения нового игрока при входе в игру, модуль проверялся включенный.
3 - Не работает локализация на команду ui. Это важно т-к локализации ЕУ будет на проекте.
4 - Список запртных подземелей (ui) нужно перенести с конфига в БД таблицу.
5 - Убрать лишние ошибки из конфига.

**Comment by Winfidonarleyan** [comment]
Можем закрыть?
