### ISSUE TITLE
Основные правки №2 [Formuls Stats]

### ISSUE THREAD

**Issue by Samaeldll** [Samaeldll/Corew#6]
1 - Нужен патч для редактирования прироста характеристик, а именно:

~~Ловкость к Силе Атаки (Как ближнего так и Дальнего)~~
~~Ловкость К Броне~~
~~Ловкость к Уклонению~~
~~Ловкость к Криту~~

~~Интеллект к Крит.Маг.~~
~~Интеллект к Мане~~

~~Сила к Паррированю [DK] (спелл)~~
~~Сила к Блоку [Paladin, Shaman, Warrior]~~
~~Сила к Блокированию~~

Реализовать нужно через базу, чтобы была возможность указать: Характеристику и прирост (по формуле или по значению). И так-же добавить сюда возможность указать максимальное значение характеристики
Пример оформления таблицы в базе данных:
Характеристика | Прирост| Максимальное значение
Ловкость            | 0.01        |  99.9%

**Comment by Winfidonarleyan** [comment]
https://github.com/Samaeldll/Corew/commit/f113d9b5372fd0048925611f76763d4e9603a9a6
