### ISSUE TITLE
Основные Правки №4 [Custom Questions]

### ISSUE THREAD

**Issue by Samaeldll** [Samaeldll/Corew#8]
Нужно реализовать уникальные условия для выполнения заданий:

- "Использовать заклинание", игрок должен использовать определенное заклинание N-нное количество раз.

- "Выиграть поле боя id/all " -  игрок должен победить N-нное количество раз на поле боя определенного типа или всех

- "Выиграть арену 1х1 / 2x2" - игрок должен победить N-нное количество раз на арене определенного типа

- "Выполнить достижение" - игрок должен выполнить достижение по id

- "Выполнить другое задание id" - игрок должен выполнить задание по Id

- "Одеть определенный предмет" - игрок должен одеть определенный предмет который определяется Guild or ID.

......

**Comment by Samaeldll** [comment]
"Одеть определенный предмет" - quest_abbadon container erase (Возможность многоразового одевания предмета)

**Comment by Samaeldll** [comment]
"Одеть определенный предмет" - при взяти квеста проверить одет ли данный предмет на игроке, чтобы игроку не приходилось переодевать предмет.
"Выполнить другое задание id" - ежедневные, еженедельные, ежемесячные, ежесезонные - не засчитываются если игрок взял квест ДО выполнения задания из категории описаной ранее.

**Comment by Winfidonarleyan** [comment]
5fbb45dffb7016f0e77e37c02be8e331138555b3
